import './js/header';
import './js/bestsellers';
import './js/filter';
import './js/categories';
import './js/theme-dark-light';
import './js/support/support';
import './js/modalcardbook';
import './js/modal-auth';
import { showLoader, hideLoader } from './js/loader';
import { toTopBtn, btnUpWrapper } from './js/scroll-up';
